apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  annotations:
    templates.weave.works/create-request: '{"repository_url":"https://github.com/priyanka-ravi/tfc-wge-demo","head_branch":"wge-create-branch-yxd1up","title":"Creates
      resource tfc-wge-demo","description":"This PR creates a tfc-demo instance","template_name":"tfc-demo","parameter_values":{"AWS_REGION":"us-east-1","CAPACITY_TYPE":"ON_DEMAND","CLUSTER_NAME":"tfc-wge-demo","CLUSTER_VERSION":"1.24","DESIRED_SIZE":"2","INSTANCE_TYPE":"t3.medium","MAX_SIZE":"3","MIN_SIZE":"1","PRIVATE_SUBNET_COUNT":"3","PUBLIC_SUBNET_COUNT":"3","VPC_CIDR":"10.0.0.0/16"},"commit_message":"Creates
      tfc-demo instance","credentials":{},"template_namespace":"default","template_kind":"GitOpsTemplate"}'
  labels:
    templates.weave.works/template-name: tfc-demo
    templates.weave.works/template-namespace: default
  name: tfc-wge-demo-core
  namespace: flux-system
spec:
  approvePlan: auto
  cliConfigSecretRef:
    name: tfc-cli-config
  cloud:
    hostname: app.terraform.io
    organization: terraform-controller-demo
    workspaces:
      name: tfc-wge-demo-core
  destroyResourcesOnDeletion: false
  interval: 1h
  path: ./terraform/cluster-templates/core
  retryInterval: 20s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
  - name: cluster_name
    value: tfc-wge-demo
  - name: cluster_version
    value: "1.24"
  - name: region
    value: us-east-1
  - name: vpc_cidr
    value: 10.0.0.0/16
  - name: public_subnet_count
    value: "3"
  - name: private_subnet_count
    value: "3"
  writeOutputsToSecret:
    name: tfc-wge-demo-core-outputs

---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  labels:
    templates.weave.works/template-name: tfc-demo
    templates.weave.works/template-namespace: default
  name: tfc-wge-demo-config
  namespace: flux-system
spec:
  approvePlan: auto
  cliConfigSecretRef:
    name: tfc-cli-config
  cloud:
    hostname: app.terraform.io
    organization: terraform-controller-demo
    workspaces:
      name: tfc-wge-demo-config
  dependsOn:
  - name: tfc-wge-demo-core
  destroyResourcesOnDeletion: false
  interval: 1h
  path: ./cluster-templates/config
  retryInterval: 20s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
  - name: cluster_name
    value: tfc-wge-demo
  - name: region
    value: us-east-1
  - name: desired_size
    value: "2"
  - name: min_size
    value: "1"
  - name: max_size
    value: "3"
  - name: capacity_type
    value: ON_DEMAND
  - name: instance_type
    value: t3.medium
